app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::group(['middleware' => 'auth'],function(){

	Route::get('/', function () {
		$meses = [
		'01'=>'Enero', 
		'02'=>'Febrero', 
		'03'=>'Marzo', 
		'04'=>'Abril', 
		'05'=>'Mayo',
		'06'=>'Junio',
		'07'=>'Julio',
		'08'=>'Agosto',
		'09'=>'Septiembre',
		'10'=>'Octubre',
		'11'=>'Noviembre',
		'12'=>'Diciembre',
		];
		for ($i=2017; $i <= date('Y'); $i++) { 
			$anios[$i] = $i;
		}
		return view('dashboard.index')->with('meses', $meses)->with('anios', $anios);
	});

	

	Route::group(['middleware'=>'admin'],function(){
		Route::get('/mantenimiento', function() {
			return view('dashboard.mantenimiento.index');
		});

		Route::put('categorias/select', 'CategoriasController@updateSelect');
		Route::delete('categorias/select', 'CategoriasController@destroySelect');
		Route::get('categorias/catalago', 'CategoriasController@catalago');
		Route::get('categorias/listar', 'CategoriasController@listar');
		Route::resource('categorias', 'CategoriasController');

		


		Route::put('departamentos/select', 'DepartamentosController@updateSelect');
		Route::delete('departamentos/select', 'DepartamentosController@destroySelect');
		Route::get('departamentos/listar', 'DepartamentosController@listar');
		Route::resource('departamentos', 'DepartamentosController');

		Route::put('prioridades/select', 'PrioridadesController@updateSelect');
		Route::delete('prioridades/select', 'PrioridadesController@destroySelect');
		Route::get('prioridades/listar', 'PrioridadesController@listar');
		Route::resource('prioridades', 'PrioridadesController');

		Route::put('usuarios/select', 'UsuariosController@updateSelect');
		Route::delete('usuarios/select', 'UsuariosController@destroySelect');
		Route::get('usuarios/listar', 'UsuariosController@listar');
		Route::resource('usuarios', 'UsuariosController');

		Route::put('incidentesoporte/select', 'IncidenteSoporteController@updateSelect');
		Route::delete('incidentesoporte/select', 'IncidenteSoporteController@destroySelect');
		Route::get('incidentesoporte/listar/{option?}', 'IncidenteSoporteController@listar');
		Route::get('incidentesoporte/tomar/{id?}', 'IncidenteSoporteController@tomar');
		Route::put('incidentesoporte/tomarselect', 'IncidenteSoporteController@tomarSelect');

		Route::put('incidentesoporte/transferencia', 'IncidenteSoporteController@transferencia');
		Route::put('incidentesoporte/transferenciaselect', 'IncidenteSoporteController@transfereciaSelect');
		Route::resource('incidentesoporte', 'IncidenteSoporteController');

		Route::get('incidentecerrados', function(){
			return view('dashboard.incidenteSoporteCerrado.index');
		});

	});
    Route::get('categorias-by-padre/{id}', 'CategoriasController@categoriasByPadre');

	Route::put('incidentecliente/select', 'IncidentesClientesController@updateSelect');
	Route::delete('incidentecliente/select', 'IncidentesClientesController@destroySelect');
	Route::get('incidentecliente/listar', 'IncidentesClientesController@listar');
	Route::resource('incidentecliente', 'IncidentesClientesController');

	Route::get('basesconocimientos/listar/{cadena?}', 'BasesConocimintosController@listar');
	Route::resource('basesconocimientos', 'BasesConocimintosController');

	Route::get('estadisticas/incidentes/{mes?}/{anio?}', 'EstadisticasController@incidentes');
	Route::get('estadisticas/incidentes-departamentos/{mes?}/{anio?}', 'EstadisticasController@incidentesDepartamento');
	Route::get('estadisticas/incidentes-departamentos-total', 'EstadisticasController@incidentesDepartamentoTotal');

	Route::get('perfil/index',[
		'uses' => 'PerfilesController@index',
		'as' => 'perfil.index'
		]
		);
	Route::post('perfil/update/{user}',[
		'uses' => 'PerfilesController@update',
		'as' => 'perfil.update'
		]
		);

});

// Authentication routes...
Route::get('login', 'Auth\AuthController@getLogin');
Route::post('login', [
	'uses' => 'Auth\AuthController@postLogin',
	'as' => 'auth.login'
	]);
Route::get('logout', [
	'uses' => 'Auth\AuthController@getLogout',
	'as' => 'auth.logout'
	]);

// Registration routes...
Route::get('register', 'Auth\AuthController@getRegister');

Route::post('register', [
	'uses' => 'Auth\AuthController@postRegister',
	'as' => 'auth.register'
	]);


// Password reset link request routes...
Route::get('password/email', [
	'uses' => 'Auth\PasswordController@getEmail',
	'as'   => 'password.email.index'
	] );

Route::post('password/email', [
	'uses' => 'Auth\PasswordController@postEmail',
	'as'   => 'password.email'
	] );


Route::post('password/reset', [
	'uses' => 'Auth\PasswordController@postReset',
	'as'   => 'password.reset'
	] );

resources/views/dashboard/templates/partials/header.blade.php
<header class="main-header">
	<!-- Logo -->
	<a href="{{ url() }}" class="logo">
		<!-- mini logo for sidebar mini 50x50 pixels -->
		<span class="logo-mini"><img src="{{ asset('img/logo.png') }}" class="img-responsive" alt="Image"></span>
		<!-- logo for regular state and mobile devices -->
		<span class="logo-lg"><b>Amazonas</b>Tech</span>
	</a>
	<!-- Header Navbar: style can be found in header.less -->
	<nav class="navbar navbar-static-top" role="navigation">
		<!-- Sidebar toggle button-->
		<a href="#" class="sidebar-toggle" data-toggle="offcanvas" role="button">
			<span class="sr-only">Toggle navigation</span>
		</a>
		<div class="navbar-custom-menu">
			<ul class="nav navbar-nav">				
				<!-- User Account: style can be found in dropdown.less -->
				<li class="dropdown user user-menu">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown">
						<img src="{{ asset('dist/img/person-icon-150x150.png') }}" class="user-image" alt="User Image">
						<span class="hidden-xs">{{ Auth::user()->name.' '.Auth::user()->apellido }}</span>
					</a>
					<ul class="dropdown-menu">
						<!-- User image -->
						<li class="user-header">
							<img src="{{ asset('dist/img/person-icon-150x150.png') }}" class="img-circle" alt="User Image">
							<p>
								{{ Auth::user()->name.' '.Auth::user()->apellido }}
								<small>{{ Auth::user()->rol->nombre }}</small>
								
							</p>
						</li>
						
						<!-- Menu Footer-->
						<li class="user-footer">
							<div class="pull-left">
								<a href="{{ url('perfil/index') }}" class="btn btn-default btn-flat pull-left">
									Perfil
								</a>
							</div>
							<div class="pull-right">
								<a href="{{ route('auth.logout') }}" class="btn btn-default btn-flat pull-right">
									Salir
								</a>
							</div>



						</li>
					</ul>
				</li>
			</ul>
		</div>
	</nav>
</header>

resources/views/dashboard/templates/partials/sidebar.blade.php
<!-- Left side column. contains the logo and sidebar -->
<aside class="main-sidebar">
	<!-- sidebar: style can be found in sidebar.less -->
	<section class="sidebar">
		<!-- Sidebar user panel -->
		<div class="user-panel">
			<div class="pull-left image">
				<img src="{{ asset('dist/img/person-icon-150x150.png') }}" class="img-circle" alt="User Image">
			</div>
			<div class="pull-left info">
				<p>{{ Auth::user()->name.' '.Auth::user()->apellido }}</p>
				<a href="#"><i class="fa fa-circle text-success"></i> Online</a>
			</div>
		</div>
		
		<!-- sidebar menu: : style can be found in sidebar.less -->
		<ul class="sidebar-menu">
			<li class="header">MENU</li>

			@if(Auth::user()->rol_id == 3)

			<li><a href="{{ url('usuarios') }}"><i class="fa fa-group  text-red"></i> <span>Gestión de Usuarios</span></a></li>

			

			<li class="{{Request::is('incidentesoporte')?'active':''}} treeview">
				<a href="#"><i class="fa fa-life-bouy text-yellow"></i> <span>Gestión de Incidentes</span> <i class="fa fa-angle-left pull-right"></i></a>
				<ul class="treeview-menu">

					<li><a href="{{ route('incidentesoporte.index') }}"><i class="fa fa-circle-o"></i> <span>Incidentes Pendientes</span></a></li>

					<li><a href="{{ url('incidentecerrados') }}"><i class="fa fa-circle-o"></i> <span>Incidentes Cerrados</span></a></li>
					
				</ul>
			</li>

			<li><a href="{{ url('mantenimiento') }}"><i class="fa fa-cog text-teal"></i> <span>Modulo de Mantenimiento</span></a></li>

			@else

			<li><a href="{{ route('incidentecliente.index') }}"><i class="fa fa-life-bouy text-yellow"></i> <span>Gestión de Incidentes</span></a></li>
			
			@endif
			<li><a href="{{ route('basesconocimientos.index') }}"><i class="fa fa-book text-aqua"></i> <span>Bases de Conocimiento</span></a></li>
			

			
		</ul>
	</section>
	<!-- /.sidebar -->
</aside> 