app/Http/routes.php
<?php

/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::group(['middleware' => 'auth'],function(){

	Route::get('/', function () {
		$meses = [
		'01'=>'Enero', 
		'02'=>'Febrero', 
		'03'=>'Marzo', 
		'04'=>'Abril', 
		'05'=>'Mayo',
		'06'=>'Junio',
		'07'=>'Julio',
		'08'=>'Agosto',
		'09'=>'Septiembre',
		'10'=>'Octubre',
		'11'=>'Noviembre',
		'12'=>'Diciembre',
		];
		for ($i=2017; $i <= date('Y'); $i++) { 
			$anios[$i] = $i;
		}
		return view('dashboard.index')->with('meses', $meses)->with('anios', $anios);
	});

	

	Route::group(['middleware'=>'admin'],function(){
		Route::get('/mantenimiento', function() {
			return view('dashboard.mantenimiento.index');
		});

		Route::put('categorias/select', 'CategoriasController@updateSelect');
		Route::delete('categorias/select', 'CategoriasController@destroySelect');
		Route::get('categorias/catalago', 'CategoriasController@catalago');
		Route::get('categorias/listar', 'CategoriasController@listar');
		Route::resource('categorias', 'CategoriasController');

		


		Route::put('departamentos/select', 'DepartamentosController@updateSelect');
		Route::delete('departamentos/select', 'DepartamentosController@destroySelect');
		Route::get('departamentos/listar', 'DepartamentosController@listar');
		Route::resource('departamentos', 'DepartamentosController');

		Route::put('prioridades/select', 'PrioridadesController@updateSelect');
		Route::delete('prioridades/select', 'PrioridadesController@destroySelect');
		Route::get('prioridades/listar', 'PrioridadesController@listar');
		Route::resource('prioridades', 'PrioridadesController');

		Route::put('usuarios/select', 'UsuariosController@updateSelect');
		Route::delete('usuarios/select', 'UsuariosController@destroySelect');
		Route::get('usuarios/listar', 'UsuariosController@listar');
		Route::resource('usuarios', 'UsuariosController');

		Route::put('incidentesoporte/select', 'IncidenteSoporteController@updateSelect');
		Route::delete('incidentesoporte/select', 'IncidenteSoporteController@destroySelect');
		Route::get('incidentesoporte/listar/{option?}', 'IncidenteSoporteController@listar');
		Route::get('incidentesoporte/tomar/{id?}', 'IncidenteSoporteController@tomar');
		Route::put('incidentesoporte/tomarselect', 'IncidenteSoporteController@tomarSelect');

		Route::put('incidentesoporte/transferencia', 'IncidenteSoporteController@transferencia');
		Route::put('incidentesoporte/transferenciaselect', 'IncidenteSoporteController@transfereciaSelect');
		Route::resource('incidentesoporte', 'IncidenteSoporteController');

		Route::get('incidentecerrados', function(){
			return view('dashboard.incidenteSoporteCerrado.index');
		});

	});
    Route::get('categorias-by-padre/{id}', 'CategoriasController@categoriasByPadre');

	Route::put('incidentecliente/select', 'IncidentesClientesController@updateSelect');
	Route::delete('incidentecliente/select', 'IncidentesClientesController@destroySelect');
	Route::get('incidentecliente/listar', 'IncidentesClientesController@listar');
	Route::resource('incidentecliente', 'IncidentesClientesController');

	Route::get('basesconocimientos/listar/{cadena?}', 'BasesConocimintosController@listar');
	Route::resource('basesconocimientos', 'BasesConocimintosController');

	Route::get('estadisticas/incidentes/{mes?}/{anio?}', 'EstadisticasController@incidentes');
	Route::get('estadisticas/incidentes-departamentos/{mes?}/{anio?}', 'EstadisticasController@incidentesDepartamento');
	Route::get('estadisticas/incidentes-departamentos-total', 'EstadisticasController@incidentesDepartamentoTotal');

	Route::get('perfil/index',[
		'uses' => 'PerfilesController@index',
		'as' => 'perfil.index'
		]
		);
	Route::post('perfil/update/{user}',[
		'uses' => 'PerfilesController@update',
		'as' => 'perfil.update'
		]
		);

});

// Authentication routes...
Route::get('login', 'Auth\AuthController@getLogin');
Route::post('login', [
	'uses' => 'Auth\AuthController@postLogin',
	'as' => 'auth.login'
	]);
Route::get('logout', [
	'uses' => 'Auth\AuthController@getLogout',
	'as' => 'auth.logout'
	]);

// Registration routes...
Route::get('register', 'Auth\AuthController@getRegister');

Route::post('register', [
	'uses' => 'Auth\AuthController@postRegister',
	'as' => 'auth.register'
	]);


// Password reset link request routes...
Route::get('password/email', [
	'uses' => 'Auth\PasswordController@getEmail',
	'as'   => 'password.email.index'
	] );

Route::post('password/email', [
	'uses' => 'Auth\PasswordController@postEmail',
	'as'   => 'password.email'
	] );


Route::post('password/reset', [
	'uses' => 'Auth\PasswordController@postReset',
	'as'   => 'password.reset'
	] );

app/Http/Controllers/IncidentesClientesController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;

use App\Http\Requests;
use App\Http\Controllers\Controller;

use App\Http\Requests\IncidenteRequest;

use Yajra\Datatables\Datatables;
use Laracasts\Flash\Flash;

use Auth;
use DB;
use Log;
use Exception;

use App\Incidente;
use App\CategoriaIncidente;
use App\EstadoIncidente;
use App\Prioridad;
use App\Archivo;

class IncidentesClientesController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        return view('dashboard.incidentesCliente.index');
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        $categorias = CategoriaIncidente::where('padre', 0)->lists('nombre', 'id');
        $prioridades = Prioridad::lists('nombre', 'id');
        return view('dashboard.incidentesCliente.form')->with('categorias', $categorias)->with('prioridades', $prioridades);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(IncidenteRequest $request)
    {

        DB::beginTransaction();
        try {
            $incidente = new Incidente($request->all());

            if(isset($request->sub_categoria)){
                $categoria = $request->sub_categoria;
            }else{
                $categoria = $request->categoria_id;
            }
            $incidente->categoria_id = $categoria;
            $incidente->user_id = Auth::user()->id;
            $incidente->estado_id = 1; // 1 es Abierto y debe de permanecer asi
            
            $incidente->save();

            foreach ($request->archivos as $i) {
                if($i != null){
                    $nombre_publico = $i->getClientOriginalName();
                    $extension = $i->getClientOriginalExtension();
                    $nombre_interno = str_replace('.'.$extension, '',$nombre_publico);
                    $nombre_interno = str_slug($nombre_interno, '-').'-'.time().'-'.strval(rand(100,999)).'.'.$extension;
                    $path_file = public_path().'/uploads/archivo';

                    $archivo = new Archivo([
                        'nombre_publico' => $nombre_publico,
                        'nombre_interno' => $nombre_interno,
                        'incidente_id' =>  $incidente->id
                        ]);
                    $archivo->save();
                    $i->move($path_file,$nombre_interno);
                }
            }
            DB::commit();
            Flash::success('Se ha creado su incidencia satisfactoriamente, será resuelta a la brevedad.');
            return redirect()->route('incidentecliente.index');
        } catch (\Exception $e) {
            DB::rollback();
            Log::error('Ha ocurrido un error en IncidentesController: '.$e->getMessage().', Linea: '.$e->getLine());
            Flash::error('Ha ocurrido un error al tratar de registrar su incidencia.');
            $categorias = CategoriaIncidente::where('padre', 0)->lists('nombre', 'id');
            $prioridades = Prioridad::lists('nombre', 'id');
            return view('dashboard.incidentesCliente.form')
            ->with('incidente', $request)
            ->with('categorias', $categorias)
            ->with('prioridades', $prioridades);
        }
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        try {
            $incidente = Incidente::findOrFail($id);
            $incidente->user;
            $incidente->responsable;
            $incidente->categoria;
            $incidente->prioridad;
            $incidente->estado;
            $incidente->archivos;
            return response()->json($incidente);
        } catch (\Exception $e) {
            Log::error('Ha ocurrido un error en IncidentesController: '.$e->getMessage().', Linea: '.$e->getLine());
            return response()->json([
                'message' => 'Ha ocurrido un error al tratar de obtener los datos.'
                ], 500);
        }
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {

    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(IncidenteRequest $request, $id)
    {
        DB::beginTransaction();
        try {
            $incidente = Incidente::findOrFail($id);
            $incidente->calificacion = $request->calificacion;
            $estado = EstadoIncidente::where('nombre', 'CERRADO')->first();
            $incidente->estado_id = $estado->id;
            $incidente->save();
            DB::commit();
            return response()->json($incidente);
        } catch (\Exception $e) {
            DB::rollback();
            Log::error('Ha ocurrido un error en IncidentesController: '.$e->getMessage().', Linea: '.$e->getLine());
            return response()->json([
                'message' => 'Ha ocurrido un error al tratar de guardar los datos.'
                ], 500);
        }
    }

    public function updateSelect(Request $request)
    {
        DB::beginTransaction();
        try {
            foreach ($request->ids as $id) {
                $incidente = Incidente::findOrFail($id);               
                $incidente->fill($request->all());
                $incidente->save();
            }
            DB::commit();
            return response()->json($request);
        } catch (\Exception $e) {
            DB::rollback();
            Log::error('Ha ocurrido un error en IncidentesController: '.$e->getMessage().', Linea: '.$e->getLine());
            return response()->json([
                'message' => 'Ha ocurrido un error al tratar de guardar los datos.'
                ], 500);
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        DB::beginTransaction();
        try {
            $incidente = Incidente::findOrFail($id);
            $incidente->delete();
            DB::commit();
            return response()->json($id);
        } catch (\Exception $e) {
            DB::rollback();
            Log::error('Ha ocurrido un error en IncidentesController: '.$e->getMessage().', Linea: '.$e->getLine());
            return response()->json([
                'message' => 'Ha ocurrido un error al tratar de eliminar los datos.'
                ], 500);
        }
    }

    public function destroySelect(Request $request)
    {
        DB::beginTransaction();
        try {
            foreach ($request->ids as $id) {
                $incidente = Incidente::findOrFail($id);
                $incidente->delete();
            }
            DB::commit();
            return response()->json($request);
        } catch (\Exception $e) {
            DB::rollback();
            Log::error('Ha ocurrido un error en IncidentesController: '.$e->getMessage().', Linea: '.$e->getLine());
            return response()->json([
                'message' => 'Ha ocurrido un error al tratar de optener los datos.'
                ],404);
        }
    }


    public function listar()
    {
        try {
            $incidentes = Incidente::where('user_id', Auth::user()->id)->get();
            $incidentes->each(function($incidentes){
                $incidentes->user;
                $incidentes->responsable;
                $incidentes->categoria;
                $incidentes->prioridad;
                $incidentes->estado;
                $incidentes->archivos;
                return $incidentes;
            });
            return Datatables::of($incidentes)->make(true);
        } catch (\Exception $e) {
            Log::error('Ha ocurrido un error en IncidentesController: '.$e->getMessage().', Linea: '.$e->getLine());
            return Datatables::of([])->make(true);
        }
    }
}

resources/views/dashboard/incidentesCliente/form.blade.php
@extends('dashboard.templates.main')

@section('css')

<link rel="stylesheet" type="text/css" href="{{ asset('plugins/bootstrap-fileinput-master/css/fileinput.css') }}">

@endsection

@section('title_page', (isset($incidente->id)?'Editar Ticket ('.$incidente->problema.')':'Nuevo Ticket') )

@section('breadcrumb')
<li><a href="{{route('incidentecliente.index')}}">Incidentes</a></li>
<li class="active">Nuevo Ticket</li>
@endsection 

@section('contenido')
<section class="content-fluid">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<div class="box box-solid">
				<div class="box-header with-border">
					<h3 class="box-title">Nuevo Ticket</h3>
				</div>
				<div class="box-body pad">
					@if(isset($incidente->id))
					{!! Form::open(['route'=>['incidentecliente.update',$incidente],'method'=>'PUT', 'files'=>true, 'class'=>'form-horizontal','enctype'=>"multipart/form-data"]) !!}
					{!! Form::hidden('id', $incidente->id) !!}  
					@else
					{!! Form::open(['route'=>'incidentecliente.store','method'=>'POST', 'files'=>true, 'class'=>'form-horizontal','enctype'=>"multipart/form-data"]) !!}  
					@endif
					<br>
					{!! Form::hidden('_token', csrf_token(), ['id'=>'token']) !!}


					<div class="form-group{{ $errors->has('categoria_id')?' has-error':'' }}">
						<div class="col-md-3">
							<div class="pull-right">
								{!! Form::label('categoria_id', 'Categoria:',['class'=>'control-label']) !!}<span style="color:red;"> *</span>
							</div>
						</div>
						<div class="col-md-9">
							{!! Form::select('categoria_id', $categorias ,(isset($incidente)?$incidente->categoria_id:null), ['id'=>'categoria_id', 'class'=>'form-control', 'placeholder'=>'-Seleccione-','required']) !!}
							@if($errors->has('categoria_id'))
							<span class="text-danger">
								<strong>{{ $errors->first('categoria_id')}}</strong>
							</span>
							@endif
						</div>
					</div>

					<div id="box-sub-categorias">
						
					</div>


					<div class="form-group{{ $errors->has('problema')?' has-error':'' }}">
						<div class="col-md-3">
							<div class="pull-right">
								{!! Form::label('problema', 'Problema:',['class'=>'control-label']) !!}<span style="color:red;"> *</span>
							</div>
						</div>
						<div class="col-md-9">
							{!! Form::text('problema', (isset($incidente)?$incidente->problema:null), ['id'=>'problema', 'class'=>'form-control', 'placeholder'=>'Problema','required']) !!}
							@if($errors->has('problema'))
							<span class="text-danger">
								<strong>{{ $errors->first('problema')}}</strong>
							</span>
							@endif
						</div>
					</div>

					<div class="form-group{{ $errors->has('descripcion')?' has-error':'' }}">
						<div class="col-md-3">
							<div class="pull-right">
								{!! Form::label('descripcion', 'Descripción:',['class'=>'control-label']) !!}<span style="color:red;"> *</span>
							</div>
						</div>
						<div class="col-md-9">
							{!! Form::textarea('descripcion', (isset($incidente)?$incidente->prefijo_telefonico:null), ['id'=>'descripcion', 'class'=>'form-control', 'placeholder'=>'Descripcion','required', 'rows'=>3]) !!}
							@if($errors->has('descripcion'))
							<span class="text-danger">
								<strong>{{ $errors->first('descripcion')}}</strong>
							</span>
							@endif
						</div>
					</div>

					<div class="form-group{{ $errors->has('archivos')?' has-error':'' }}">
						<div class="col-md-3">
							<div class="pull-right">
								{!! Form::label('archivos', 'Archivo(s):',['class'=>'control-label']) !!}
							</div>
						</div>
						<div class="col-md-9">
							<input type="file" name="archivos[]" id='archivos' multiple="">
							@if($errors->has('archivos'))
							<span class="text-danger">
								<strong>{{ $errors->first('archivos')}}</strong>
							</span>
							@endif
						</div>
					</div>

					<div class="form-group{{ $errors->has('prioridad_id')?' has-error':'' }}">
						<div class="col-md-3">
							<div class="pull-right">
								{!! Form::label('prioridad_id', 'Prioridad:',['class'=>'control-label']) !!}<span style="color:red;"> *</span>
							</div>
						</div>
						<div class="col-md-9">
							{!! Form::select('prioridad_id', $prioridades ,(isset($incidente)?$incidente->prioridad_id:null), ['id'=>'prioridad_id', 'class'=>'form-control','required']) !!}
							@if($errors->has('prioridad_id'))
							<span class="text-danger">
								<strong>{{ $errors->first('prioridad_id')}}</strong>
							</span>
							@endif
						</div>
					</div>

					
					<hr>

					<div class="form-group">
						<div class="col-md-12">
							<a href="{{route('incidentecliente.index')}}" class="btn btn-warning btn-sm">Cancelar</a>
							{!! Form::submit('Guardar Cambios',['class'=>'btn btn-primary btn-sm pull-right']) !!}
						</div>
					</div>
					{!! Form::close() !!} 
				</div>
			</div>
		</div>
		
	</div>
</section>


@endsection

@section('js')

<script src="{{asset('plugins/bootstrap-fileinput-master/js/fileinput.js')}}"></script>
<script src="{{asset('plugins/bootstrap-fileinput-master/js/locales/es.js')}}"></script>


<script type="text/javascript">

	$('#archivos').fileinput({
		showUpload: false,
		language: 'es'
	});

	function soloLetras(e){
		key = e.keyCode || e.which;
		tecla = String.fromCharCode(key).toLowerCase();
		letras = " áéíóúabcdefghijklmnñopqrstuvwxyz";
		especiales = "8-37-39-46";

		tecla_especial = false
		for(var i in especiales){
			if(key == especiales[i]){
				tecla_especial = true;
				break;
			}
		}

		if(letras.indexOf(tecla)==-1 && !tecla_especial){
			return false;
		}
	}

	$('#categoria_id').change(function(){
		
		if($(this).val() != 0){
			$.ajax({
				url: ruta+'/categorias-by-padre/'+$(this).val(),
				type: 'GET',
				success: function(res){ 
					var html = '<div class="form-group">'+
					'<div class="col-md-3">'+
					'<div class="pull-right">'+
					'<label class="control-label">Sub-categoria: <span style="color:red;"> *</span></label>'+
					'</div>'+
					'</div>'+
					'<div class="col-md-9">'+
					'<select name="sub_categoria" id="sub_categoria" class="form-control">';

					for(var i = 0; i<res.length; i++){
						html+='<option value="'+res[i].id+'">'+res[i].nombre+'</opction>';
					}

					html+='</select>'+
					'</div>'+
					'</div>';

					$('#box-sub-categorias').append(html);
				},
				error: function(jqXHR, textStatus, errorThrown) {
					sweetAlert(
						'Error',
						'Ha ocurrido un error al tratar de obtener los datos de la categoria. Status: '+jqXHR.status,
						'error'
						)
				}
			});
		}else{
			$('#box-sub-categorias').html("");
		}
		
	});

</script>
@endsection

resources/views/dashboard/incidentesCliente/formCalificar.blade.php
<!-- Modal -->
<div class="modal fade" id="modal-form-incidente" data-keyboard="false" data-backdrop="static">
	<div class="modal-dialog " role="document">
		<div class="modal-content box">

			<div class="modal-header text-center">
				{!! Form::open(['id'=>'form-incidente']) !!}
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title">Calificación de Incidente</h4>
			</div>
			
			<div class="modal-body">
				<div class="row">
					<div class="form-group col-sm-12" id="field-id">
						{!! Form::label('id', 'ID:',['class'=>'control-label']) !!}
						{!!Form::text('id', null, ['id'=>'id', 'class'=>'form-control', 'readonly'])!!}
					</div> 
				</div>

				<div class="row">
					<div class="form-group col-sm-12" id="field-solucion">
						{!! Form::label('solucion', 'Solución:',['class'=>'control-label']) !!}
						{!!Form::textarea('solucion', null, ['id'=>'solucion', 'class'=>'form-control', 'rows'=>2, 'readonly'])!!}
						<span>
							<strong class="text-danger msj-error"></strong>
						</span>
					</div>
				</div>
				<hr>
		
				<div class="row">
					<div class="form-group col-sm-12">
						<h3>Califique el servicio</h3>

						<div class="radio">
							<label>
								<input name="calificacion" id="optionsRadios1" value="Excelente" checked="" type="radio">
								Excelente
							</label>&nbsp&nbsp

							<label>
								<input name="calificacion" id="optionsRadios2" value="Bueno" type="radio">
								Bueno
							</label>&nbsp&nbsp

							<label>
								<input name="calificacion" id="optionsRadios2" value="Regular" type="radio">
								Regular
							</label>&nbsp&nbsp

							<label>
								<input name="calificacion" id="optionsRadios2" value="Malo" type="radio">
								Malo
							</label>&nbsp&nbsp
						</div>
					</div>
				</div>
				


			</div>

			<div class="modal-footer">
				<button type="button" id="guardar-incidente" class="btn btn-primary btn-sm pull-left" data-loading-text="Guardando..." autocomplete="off">Guardar</button>
				<button type="button" class="btn btn-default btn-sm" data-dismiss="modal">Cerrar</button>
			</div>
			{!! Form::close() !!}
		</div>
	</div>
</div>

resources/views/dashboard/incidentesCliente/index.blade.php
@extends('dashboard.templates.main')

@section('css')
<!-- DataTables -->
<link rel="stylesheet" type="text/css" href="{{asset('plugins/datatables/dataTables.bootstrap.css')}}">
@endsection

@section('titulo_modulo', "Incidentes")

@section('contenido')
<div class="row">
	<input type="hidden" name="_token" id="token" value="{{ csrf_token() }}">
	<div class="col-sm-12">
		<div class="box box-solid">
			
			<div class="box-body">

				<a class="btn btn-default btn-sm"  data-toggle="modal" href='{{ route('incidentecliente.create') }}'><i class="fa fa-plus"></i> Abrir nuevo ticket</a>
				<a href='javascript:void(0)' class="btn btn-default btn-sm"  id="actualizar"><i class="fa fa-repeat"></i> Actualizar tabla</a>
				<hr>
				<table class="table table-bordered table-hover table-striped" id="tabla-incidentes" width="100%">
					<thead>
						<th  style="width: 32px; padding-right: 8px;">
							<input name="select_all" value="1" id="select-all" type="checkbox">
						</th>
						<th style="width: 30px;">ID</th>
						{{-- aqui ira descripcion, problema, categoria y prioridad--}}
						<th style="width: 35%">Ticket</th> 
						<th>Solución</th>
						<th>Responsable</th>
						<th>Estado</th>
						<th>Fecha de creacion</th>
						<th style="width: 50px;">Archivos</th>
					</thead>
				</table>
			</div><!-- /.box-body -->
			<div class="box-footer">
			</div><!-- /.box-footer-->
		</div><!-- /.box -->


	</div>
</div>
@include('dashboard.incidentesCliente.window')
@include('dashboard.incidentesCliente.formCalificar')



@endsection

@section('js')
<script src="{{asset('plugins/datatables/jquery.dataTables.min.js')}}"></script>
<script src="{{asset('plugins/datatables/dataTables.bootstrap.min.js')}}"></script>
<!-- InputMask -->
<script src="{{ asset('plugins/input-mask/jquery.inputmask.js') }}"></script>
<script src="{{ asset('plugins/input-mask/jquery.inputmask.date.extensions.js') }}"></script>
<script src="{{ asset('plugins/input-mask/jquery.inputmask.extensions.js') }}"></script>
<script src="{{asset('js/validate.js')}}"></script>
<script src="{{asset('js/indicentesCliente.js')}}"></script>
@endsection

resources/views/dashboard/incidentesCliente/window.blade.php
<div class="modal fade" id="modal-incidente">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-hidden="true">&times;</button>
				<h4 class="modal-title" id="titulo-modal-incidente"></h4>
			</div>
			<div class="modal-body" id="contenido-modal-incidente">
				
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-default pull-right" data-dismiss="modal">Cerrar</button>
			</div>
		</div>
	</div>
</div>